### ISSUE TITLE
App Crashes on Launch

### ISSUE THREAD

**Issue by BryanJBryce** [Swift-Flow/CounterExample#2]
dyld: Library not loaded: @rpath/ReSwift.framework/ReSwift
  Referenced from: /var/mobile/Containers/Bundle/Application/9E290F65-591B-48E0-B2B6-95B401ED3A8D/ReSwiftCounterExample.app/ReSwiftCounterExample
  Reason: image not found

**Comment by Ben-G** [comment]
@BryanJBryce Thanks for reporting this!

I assume this issue was happening when running on a device? I've updated the app to embed the binaries of the frameworks. This _should_ fix the issue; I didn't have a chance to test on device yet as I'm having a small issue with my developer account.

Let me know if this fixes the issue for you!
